import {
  defineConfig,
  presetUno,
  presetAttributify,
  presetIcons,
  transformerDirectives,
  transformerVariantGroup,
} from "unocss";

export default defineConfig({
  safelist: [
    "i-mdi:bell",
    "i-mdi:bell-outline",
    "i-mdi:heart",
    "i-mdi:heart-outline",
    "i-mdi:medal",
    "i-mdi:medal-outline",
    "i-mdi:progress-helper",
    "i-tabler:progress-bolt",
    "i-material-symbols:category-outline",
    "i-material-symbols:category",
    "i-material-symbols:fiber-new",
    "i-material-symbols:fiber-new-outline",
    "i-mdi:new-box-outline",
    "i-mdi:check-circle-outline",
    "i-mdi:check-circle",
    "i-mdi:fire",
    "md:p-2",
    "md:rounded-xl",
    "md:w-1/2",
    "lg:w-1/3",
    "md:items-start",
    "z-99999",
    "bg-black",
    "text-4xl",
    "text-green-500",
    "animate-bounce-in",
    "animate-bounce-out",
    "animate-duration-200",
    "pointer-events-none",
  ],
  presets: [presetUno(), presetIcons(), presetAttributify()],
  transformers: [transformerDirectives(), transformerVariantGroup()],
});
